let contract
let address
let rangeLow
let rangeHigh
let minABI = [
    {
       "inputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"approved",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"Approval",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"operator",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"bool",
             "name":"approved",
             "type":"bool"
          }
       ],
       "name":"ApprovalForAll",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"previousOwner",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"newOwner",
             "type":"address"
          }
       ],
       "name":"OwnershipTransferred",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"Transfer",
       "type":"event"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"approve",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"owner",
             "type":"address"
          }
       ],
       "name":"balanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"claim",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getApproved",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getChest",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getFoot",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getHand",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getHead",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getNeck",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getRing",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getWaist",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"getWeapon",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"operator",
             "type":"address"
          }
       ],
       "name":"isApprovedForAll",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"name",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"owner",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"ownerClaim",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"ownerOf",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"renounceOwnership",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"safeTransferFrom",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"_data",
             "type":"bytes"
          }
       ],
       "name":"safeTransferFrom",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"operator",
             "type":"address"
          },
          {
             "internalType":"bool",
             "name":"approved",
             "type":"bool"
          }
       ],
       "name":"setApprovalForAll",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes4",
             "name":"interfaceId",
             "type":"bytes4"
          }
       ],
       "name":"supportsInterface",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"symbol",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"index",
             "type":"uint256"
          }
       ],
       "name":"tokenByIndex",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"index",
             "type":"uint256"
          }
       ],
       "name":"tokenOfOwnerByIndex",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"tokenURI",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"totalSupply",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"tokenId",
             "type":"uint256"
          }
       ],
       "name":"transferFrom",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"newOwner",
             "type":"address"
          }
       ],
       "name":"transferOwnership",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]



var web3 = new Web3(Web3.givenProvider || 'https://mainnet.infura.io/v3/4a200a3f339c403a8c2aa708873f5a5c');
window.onload = function(){
    document.getElementById('enableEthereumButton').addEventListener('click', function(){
        getAccount();
    });


    document.getElementById("click").addEventListener("click", function() {
        var div = document.getElementById("data");
        console.log(div.firstChild)
        while(div.firstChild){
        div.removeChild(div.firstChild);
}
        address = document.getElementById("input").value
        console.log(address)
        contract = new web3.eth.Contract(minABI,address);
        if (document.getElementById("rangeLow").value !=""){
            rangeLow = document.getElementById("rangeLow").value
        }else{
            rangeLow = 1
        }
        if (document.getElementById("rangeHigh").value !=""){
            rangeHigh = document.getElementById("rangeHigh").value
        }else{
            rangeHigh = 10000
        }

        console.log(rangeLow, rangeHigh)
        for (let i=rangeLow;i<=rangeHigh;i++){
            console.log(i)
            getOwnerOfTokenID(i).then(function (result) {
                console.log(result)
                para = document.createElement("p")
                if (result.length != 42){
                    para.innerHTML = "id "+i+" is FREE!"
                    document.getElementById("data").prepend(para)
                }else{
                    para.innerHTML = "id "+i+" owned by "+result
                    document.getElementById("data").append(para)
                }
            })
        }


    })
}

async function getOwnerOfTokenID(id){
    ownerOf = await contract.methods.ownerOf(id).call()
    return ownerOf
}

async function getAccount() {
    accounts = await ethereum.request({ method: 'eth_requestAccounts' });
    document.getElementById('enableEthereumButton').innerHTML = "Connected " + accounts[0].slice(0,5) + "..."
    web3.eth.net.getNetworkType().then(response => {

        document.getElementById('networkInfo').innerHTML = "Connected to " +response




    })

}