let nounAddress = "0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03"
let nounTreasuryAddress = "0x0BC3807Ec262cB779b38D65b38158acC3bfedE10"
let sharkDAOAddress = "0xAe7f458667f1B30746354aBC3157907d9F6FD15E"
let ticketBooth = "0xee2eBCcB7CDb34a8A822b589F9E8427C24351bfc"
let fundingCycles = "0xf507B2A1dD7439201eb07F11E1d62AfB29216e2E"
let terminalV1 = "0xd569D3CCE55b71a8a3f3C418c329A66e5f714431"
let sushiSwapPoolAddress = "0x2240EF04Bb3e2601977D2d47Aa3287628aD71156"
let USDCETHPoolAddress = "0x397FF1542f962076d0BFE58eA045FfA2d347ACa0"
let nounSupply = 0;
let nounsDaoTreasurySize = 0;
let sharkTokenTotalSupply
let fundingCycleWeight
let overflow
let sharkDAOEthBalance
let nounsDAOnounBalance
let sharkDAOnounBalance
let untappedBalance
let ethUSDPrice
let tokenPrice

var app = new Vue({
    el: '#app',
        data: {
        sharkdaoeth: 0,
        sharkdaonouns: 0,
        nounsdaoeth:     0,
        nounsdaonouns: 0,
        nounsupply: 0,
        fairprice: 0,
        valuation:0,
        sharktokensupply:0,
        tokensforeth:0,
        sharkdaonounvaluation:0,
        message: "",
        message2: "",
        sharktokenpriceUSD:0,
        sharktokenpriceETH:0,
        marketcap:0,
        sharkdaoethusd:0,
        marketcapminuseth:0,
        nounusdvaluation:0

        }
        
    })




let minABI = [
    // balanceOf
    {
      "constant":true,
      "inputs":[{"name":"_owner","type":"address"}],
      "name":"balanceOf",
      "outputs":[{"name":"balance","type":"uint256"}],
      "type":"function"
    },
    // decimals
    {
      "constant":true,
      "inputs":[],
      "name":"decimals",
      "outputs":[{"name":"","type":"uint8"}],
      "type":"function"
    },
    // total supply
    {
        "constant": true,
        "inputs": [],
        "name": "totalSupply",
        "outputs": [
            {
                "name": "",
                "type": "uint256"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    }
  ];


let fundingCycleABI = [
    {
       "inputs":[
          {
             "internalType":"contract ITerminalDirectory",
             "name":"_terminalDirectory",
             "type":"address"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"prod1",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"denominator",
             "type":"uint256"
          }
       ],
       "name":"PRBMath__MulDivOverflow",
       "type":"error"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"reconfigured",
             "type":"uint256"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                }
             ],
             "indexed":false,
             "internalType":"struct FundingCycleProperties",
             "name":"_properties",
             "type":"tuple"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"metadata",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Configure",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"number",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"previous",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"weight",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"start",
             "type":"uint256"
          }
       ],
       "name":"Init",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"newTappedAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Tap",
       "type":"event"
    },
    {
       "inputs":[
          
       ],
       "name":"BASE_WEIGHT",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"MAX_CYCLE_LIMIT",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                }
             ],
             "internalType":"struct FundingCycleProperties",
             "name":"_properties",
             "type":"tuple"
          },
          {
             "internalType":"uint256",
             "name":"_metadata",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_fee",
             "type":"uint256"
          },
          {
             "internalType":"bool",
             "name":"_configureActiveFundingCycle",
             "type":"bool"
          }
       ],
       "name":"configure",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"id",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"projectId",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"number",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"basedOn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"configured",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"weight",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"start",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"fee",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"tapped",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"metadata",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycle",
             "name":"fundingCycle",
             "type":"tuple"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"count",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"currentBallotStateOf",
       "outputs":[
          {
             "internalType":"enum BallotState",
             "name":"",
             "type":"uint8"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"currentOf",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"id",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"projectId",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"number",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"basedOn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"configured",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"weight",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"start",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"fee",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"tapped",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"metadata",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycle",
             "name":"fundingCycle",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_fundingCycleId",
             "type":"uint256"
          }
       ],
       "name":"get",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"id",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"projectId",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"number",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"basedOn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"configured",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"weight",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"start",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"fee",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"tapped",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"metadata",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycle",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"latestIdOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"queuedOf",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"id",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"projectId",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"number",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"basedOn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"configured",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"weight",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"start",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"fee",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"tapped",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"metadata",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycle",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"tap",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"id",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"projectId",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"number",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"basedOn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"configured",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"weight",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"start",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"fee",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"tapped",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"metadata",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycle",
             "name":"fundingCycle",
             "type":"tuple"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"terminalDirectory",
       "outputs":[
          {
             "internalType":"contract ITerminalDirectory",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    }
 ]

 let ticketBoothABI = [
    {
       "inputs":[
          {
             "internalType":"contract IProjects",
             "name":"_projects",
             "type":"address"
          },
          {
             "internalType":"contract IOperatorStore",
             "name":"_operatorStore",
             "type":"address"
          },
          {
             "internalType":"contract ITerminalDirectory",
             "name":"_terminalDirectory",
             "type":"address"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"name",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"symbol",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Issue",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Lock",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"bool",
             "name":"convertedTickets",
             "type":"bool"
          },
          {
             "indexed":false,
             "internalType":"bool",
             "name":"preferUnstakedTickets",
             "type":"bool"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"controller",
             "type":"address"
          }
       ],
       "name":"Print",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"stakedTickets",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"bool",
             "name":"preferUnstaked",
             "type":"bool"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"controller",
             "type":"address"
          }
       ],
       "name":"Redeem",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Stake",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"recipient",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Transfer",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Unlock",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Unstake",
       "type":"event"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"balanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"balance",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"string",
             "name":"_name",
             "type":"string"
          },
          {
             "internalType":"string",
             "name":"_symbol",
             "type":"string"
          }
       ],
       "name":"issue",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"lock",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"lockedBalanceBy",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"lockedBalanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"operatorStore",
       "outputs":[
          {
             "internalType":"contract IOperatorStore",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"bool",
             "name":"_preferUnstakedTickets",
             "type":"bool"
          }
       ],
       "name":"print",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"projects",
       "outputs":[
          {
             "internalType":"contract IProjects",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"bool",
             "name":"_preferUnstaked",
             "type":"bool"
          }
       ],
       "name":"redeem",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"stake",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"stakedBalanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"stakedTotalSupplyOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"terminalDirectory",
       "outputs":[
          {
             "internalType":"contract ITerminalDirectory",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"ticketsOf",
       "outputs":[
          {
             "internalType":"contract ITickets",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"totalSupplyOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"supply",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"_recipient",
             "type":"address"
          }
       ],
       "name":"transfer",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"unlock",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_holder",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"unstake",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]




let terminalABI = [
    {
       "inputs":[
          {
             "internalType":"contract IProjects",
             "name":"_projects",
             "type":"address"
          },
          {
             "internalType":"contract IFundingCycles",
             "name":"_fundingCycles",
             "type":"address"
          },
          {
             "internalType":"contract ITicketBooth",
             "name":"_ticketBooth",
             "type":"address"
          },
          {
             "internalType":"contract IOperatorStore",
             "name":"_operatorStore",
             "type":"address"
          },
          {
             "internalType":"contract IModStore",
             "name":"_modStore",
             "type":"address"
          },
          {
             "internalType":"contract IPrices",
             "name":"_prices",
             "type":"address"
          },
          {
             "internalType":"contract ITerminalDirectory",
             "name":"_terminalDirectory",
             "type":"address"
          },
          {
             "internalType":"address payable",
             "name":"_governance",
             "type":"address"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"prod1",
             "type":"uint256"
          }
       ],
       "name":"PRBMath__MulDivFixedPointOverflow",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"prod1",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"denominator",
             "type":"uint256"
          }
       ],
       "name":"PRBMath__MulDivOverflow",
       "type":"error"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"governance",
             "type":"address"
          }
       ],
       "name":"AcceptGovernance",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"AddToBalance",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"contract ITerminal",
             "name":"allowed",
             "type":"address"
          }
       ],
       "name":"AllowMigration",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"governance",
             "type":"address"
          }
       ],
       "name":"AppointGovernance",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Configure",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"Deposit",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                },
                {
                   "internalType":"contract IModAllocator",
                   "name":"allocator",
                   "type":"address"
                },
                {
                   "internalType":"uint56",
                   "name":"projectId",
                   "type":"uint56"
                }
             ],
             "indexed":false,
             "internalType":"struct PayoutMod",
             "name":"mod",
             "type":"tuple"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"modCut",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"DistributeToPayoutMod",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                }
             ],
             "indexed":false,
             "internalType":"struct TicketMod",
             "name":"mod",
             "type":"tuple"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"modCut",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"DistributeToTicketMod",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"target",
             "type":"uint256"
          }
       ],
       "name":"EnsureTargetLocalWei",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"contract ITerminal",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Migrate",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"beneficiary",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"note",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Pay",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"beneficiary",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"currency",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"memo",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"PrintPreminedTickets",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"beneficiary",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"count",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"beneficiaryTicketAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"PrintReserveTickets",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"holder",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"beneficiary",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"returnAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Redeem",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          }
       ],
       "name":"SetFee",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"SetTargetLocalWei",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"contract IYielder",
             "name":"newYielder",
             "type":"address"
          }
       ],
       "name":"SetYielder",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"fundingCycleId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"uint256",
             "name":"projectId",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"beneficiary",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"currency",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"netTransferAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"beneficiaryTransferAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"govFeeAmount",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"caller",
             "type":"address"
          }
       ],
       "name":"Tap",
       "type":"event"
    },
    {
       "inputs":[
          
       ],
       "name":"acceptGovernance",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"addToBalance",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"contract ITerminal",
             "name":"_contract",
             "type":"address"
          }
       ],
       "name":"allowMigration",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address payable",
             "name":"_pendingGovernance",
             "type":"address"
          }
       ],
       "name":"appointGovernance",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"balanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"canPrintPreminedTickets",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_account",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_count",
             "type":"uint256"
          }
       ],
       "name":"claimableOverflowOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                }
             ],
             "internalType":"struct FundingCycleProperties",
             "name":"_properties",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"reservedRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"bondingCurveRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"reconfigurationBondingCurveRate",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycleMetadata",
             "name":"_metadata",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                },
                {
                   "internalType":"contract IModAllocator",
                   "name":"allocator",
                   "type":"address"
                },
                {
                   "internalType":"uint56",
                   "name":"projectId",
                   "type":"uint56"
                }
             ],
             "internalType":"struct PayoutMod[]",
             "name":"_payoutMods",
             "type":"tuple[]"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                }
             ],
             "internalType":"struct TicketMod[]",
             "name":"_ticketMods",
             "type":"tuple[]"
          }
       ],
       "name":"configure",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"currentOverflowOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"overflow",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_owner",
             "type":"address"
          },
          {
             "internalType":"bytes32",
             "name":"_handle",
             "type":"bytes32"
          },
          {
             "internalType":"string",
             "name":"_uri",
             "type":"string"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"target",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"currency",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"duration",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"cycleLimit",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"discountRate",
                   "type":"uint256"
                },
                {
                   "internalType":"contract IFundingCycleBallot",
                   "name":"ballot",
                   "type":"address"
                }
             ],
             "internalType":"struct FundingCycleProperties",
             "name":"_properties",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"uint256",
                   "name":"reservedRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"bondingCurveRate",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"reconfigurationBondingCurveRate",
                   "type":"uint256"
                }
             ],
             "internalType":"struct FundingCycleMetadata",
             "name":"_metadata",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                },
                {
                   "internalType":"contract IModAllocator",
                   "name":"allocator",
                   "type":"address"
                },
                {
                   "internalType":"uint56",
                   "name":"projectId",
                   "type":"uint56"
                }
             ],
             "internalType":"struct PayoutMod[]",
             "name":"_payoutMods",
             "type":"tuple[]"
          },
          {
             "components":[
                {
                   "internalType":"bool",
                   "name":"preferUnstaked",
                   "type":"bool"
                },
                {
                   "internalType":"uint16",
                   "name":"percent",
                   "type":"uint16"
                },
                {
                   "internalType":"uint48",
                   "name":"lockedUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"address payable",
                   "name":"beneficiary",
                   "type":"address"
                }
             ],
             "internalType":"struct TicketMod[]",
             "name":"_ticketMods",
             "type":"tuple[]"
          }
       ],
       "name":"deploy",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"fee",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"fundingCycles",
       "outputs":[
          {
             "internalType":"contract IFundingCycles",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"governance",
       "outputs":[
          {
             "internalType":"address payable",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"contract ITerminal",
             "name":"_to",
             "type":"address"
          }
       ],
       "name":"migrate",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"contract ITerminal",
             "name":"",
             "type":"address"
          }
       ],
       "name":"migrationIsAllowed",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"modStore",
       "outputs":[
          {
             "internalType":"contract IModStore",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"operatorStore",
       "outputs":[
          {
             "internalType":"contract IOperatorStore",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"_beneficiary",
             "type":"address"
          },
          {
             "internalType":"string",
             "name":"_memo",
             "type":"string"
          },
          {
             "internalType":"bool",
             "name":"_preferUnstakedTickets",
             "type":"bool"
          }
       ],
       "name":"pay",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"pendingGovernance",
       "outputs":[
          {
             "internalType":"address payable",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"prices",
       "outputs":[
          {
             "internalType":"contract IPrices",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_currency",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"_beneficiary",
             "type":"address"
          },
          {
             "internalType":"string",
             "name":"_memo",
             "type":"string"
          },
          {
             "internalType":"bool",
             "name":"_preferUnstakedTickets",
             "type":"bool"
          }
       ],
       "name":"printPreminedTickets",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          }
       ],
       "name":"printReservedTickets",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"projects",
       "outputs":[
          {
             "internalType":"contract IProjects",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_account",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_count",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_minReturnedWei",
             "type":"uint256"
          },
          {
             "internalType":"address payable",
             "name":"_beneficiary",
             "type":"address"
          },
          {
             "internalType":"bool",
             "name":"_preferUnstaked",
             "type":"bool"
          }
       ],
       "name":"redeem",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_reservedRate",
             "type":"uint256"
          }
       ],
       "name":"reservedTicketBalanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_fee",
             "type":"uint256"
          }
       ],
       "name":"setFee",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_projectId",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_amount",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_currency",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_minReturnedWei",
             "type":"uint256"
          }
       ],
       "name":"tap",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"terminalDirectory",
       "outputs":[
          {
             "internalType":"contract ITerminalDirectory",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"ticketBooth",
       "outputs":[
          {
             "internalType":"contract ITicketBooth",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    }
 ]

let sushiLPTokenAbi = [
    {
       "inputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"Approval",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount0",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount1",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          }
       ],
       "name":"Burn",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount0",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount1",
             "type":"uint256"
          }
       ],
       "name":"Mint",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount0In",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount1In",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount0Out",
             "type":"uint256"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount1Out",
             "type":"uint256"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          }
       ],
       "name":"Swap",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint112",
             "name":"reserve0",
             "type":"uint112"
          },
          {
             "indexed":false,
             "internalType":"uint112",
             "name":"reserve1",
             "type":"uint112"
          }
       ],
       "name":"Sync",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"Transfer",
       "type":"event"
    },
    {
       "inputs":[
          
       ],
       "name":"DOMAIN_SEPARATOR",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"MINIMUM_LIQUIDITY",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"PERMIT_TYPEHASH",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"allowance",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"approve",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"balanceOf",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          }
       ],
       "name":"burn",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amount0",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"amount1",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"decimals",
       "outputs":[
          {
             "internalType":"uint8",
             "name":"",
             "type":"uint8"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"factory",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getReserves",
       "outputs":[
          {
             "internalType":"uint112",
             "name":"_reserve0",
             "type":"uint112"
          },
          {
             "internalType":"uint112",
             "name":"_reserve1",
             "type":"uint112"
          },
          {
             "internalType":"uint32",
             "name":"_blockTimestampLast",
             "type":"uint32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_token0",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_token1",
             "type":"address"
          }
       ],
       "name":"initialize",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"kLast",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          }
       ],
       "name":"mint",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"liquidity",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"name",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"nonces",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"owner",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"spender",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"deadline",
             "type":"uint256"
          },
          {
             "internalType":"uint8",
             "name":"v",
             "type":"uint8"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"permit",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"price0CumulativeLast",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"price1CumulativeLast",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          }
       ],
       "name":"skim",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"amount0Out",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"amount1Out",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"bytes",
             "name":"data",
             "type":"bytes"
          }
       ],
       "name":"swap",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"symbol",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"sync",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"token0",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"token1",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"totalSupply",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"transfer",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"transferFrom",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]

var web3 = new Web3(Web3.givenProvider || 'https://mainnet.infura.io/v3/4a200a3f339c403a8c2aa708873f5a5c');
let contract = new web3.eth.Contract(minABI,nounAddress);
let fundingCycleContract = new web3.eth.Contract(fundingCycleABI, fundingCycles);
let ticketBoothContract = new web3.eth.Contract(ticketBoothABI, ticketBooth);
let terminalContract = new web3.eth.Contract(terminalABI, terminalV1);
let sushiSwapLP = new web3.eth.Contract(sushiLPTokenAbi, sushiSwapPoolAddress);
let sushiUSDC = new web3.eth.Contract(sushiLPTokenAbi, USDCETHPoolAddress);

//web3.eth.getBalance(sharkDAOAddress 


 //     return web3.utils.fromWei(result, "ether")


// Call balanceOf function
decimals = contract.methods.decimals()
balance = contract.methods.balanceOf(sharkDAOAddress);

async function getETHBalance(){
    ethbalance = await web3.eth.getBalance(sharkDAOAddress)
    return web3.utils.fromWei(ethbalance, "ether")
}

async function getNounsDaoEthBalance(){
    nounsDAOEthBalance = await web3.eth.getBalance(nounTreasuryAddress)
    return web3.utils.fromWei(nounsDAOEthBalance, "ether")
}

async function getSharkTokenSupply(){
    supply = await ticketBoothContract.methods.totalSupplyOf(7).call();
    return supply
}

async function getFundingCycleData(){
    data = await fundingCycleContract.methods.currentOf(7).call();
    return data
}

async function getUntappedBalance(){
    balance = await terminalContract.methods.balanceOf(7).call();
    return web3.utils.fromWei(balance, "ether")
}

async function getSharkDaoNounBalance(){
    balance = await contract.methods.balanceOf(sharkDAOAddress).call();
    return balance;
}

async function getNounsDaoNounBalance(){
    balance = await contract.methods.balanceOf(nounTreasuryAddress).call();
    return balance;
}

async function getNounSupply(){
    nouns = await contract.methods.totalSupply().call();
    return nouns;
}

function fairPrice(supply, treasury){
    if (supply == 0 || treasury == 0) {
        return 0
    }else{
    return treasury/(supply-1)
}
}

async function sharkTokenPrice(){
    result = await sushiSwapLP.methods.getReserves().call();
    return result
}

async function ethPrice(){
    result = await sushiUSDC.methods.getReserves().call();
    return result
}

getSharkTokenSupply().then(function (result) {
    sharkTokenTotalSupply = result
    app.sharktokensupply = result/1e18
})

getFundingCycleData().then(function (result) {
    fundingCycleWeight = result[6]
    app.tokensforeth = result[6]/1e18
})


getETHBalance().then(function (result) {
    sharkDAOEthBalance = result
    getUntappedBalance().then(function (result){
        app.shardaoeth = parseFloat(app.shardaoeth) + parseFloat(result)
        sharkDAOEthBalance = parseFloat(sharkDAOEthBalance) + parseFloat(result)
        app.sharkdaoeth = sharkDAOEthBalance

    })
});



getSharkDaoNounBalance().then(function(result){
    sharkDAOnounBalance = result
    app.sharkdaonouns = result
    getNounsDaoNounBalance().then(function(result){
        nounsDAOnounBalance = result
        app.nounsdaonouns = result
        getNounSupply().then(function(result){
            nounSupply = result
            app.nounsupply = result
            getNounsDaoEthBalance().then(function(result){
                nounsDaoTreasurySize = result
                app.nounsdaoeth = result
                app.fairprice = nounsDaoTreasurySize/(nounSupply-1-nounsDAOnounBalance)
                app.sharkdaonounvaluation = calculateValuation()
            })
        })
        })
        })
        
sharkTokenPrice().then(function(result){
    tokenPrice = result._reserve1/result._reserve0
    app.sharktokenpriceETH = tokenPrice
 
})

ethPrice().then(function(result){
    app.sharktokenpriceUSD = tokenPrice * ((result._reserve0/result._reserve1)*1e12)
    calculateValuation2()
})

function calculateValuation2(){
    marketCap = tokenPrice * (sharkTokenTotalSupply)
    app.marketcap = marketCap
    ethHoldingValue = sharkDAOEthBalance * ethUSDPrice
    app.sharkdaoethusd = ethHoldingValue
    marketCapWithoutEth = marketCap - ethHoldingValue
    app.marketcapminuseth = marketCapWithoutEth
    app.nounsdaovaluation = marketCapWithoutEth/sharkDAOnounBalance

}

function calculateValuation(){
    percentageForOneEth = fundingCycleWeight/sharkTokenTotalSupply
    console.log(percentageForOneEth)
    claimOfDAOEth = percentageForOneEth*sharkDAOEthBalance
    console.log(claimOfDAOEth)
    valuation = (1-claimOfDAOEth)/percentageForOneEth;
    console.log(valuation)
    valuationPerNoun = valuation/sharkDAOnounBalance
    return valuationPerNoun
}

app.message = "Calculated by:\
1. dividing shark tokens received per one eth by shark token total supply \
2. multiplying that by shark dao eth holdings (the amount of eth the shark tokens entitle you to if the eth was paid out) \
3. taking that number out of one eth (how much of your 1 eth would be left in the dao after payout) \
4. multiplying result by percentage calculated at step 1 \
5. multiplying that by amount of nouns that the shark dao holds"

app.message2 = "Calculated by dividing the nouns dao treasury eth amount by noun supply (not taking account the current unsold noun). \
Possible nounsdao noun holdings are also taken into account and subtracted from the total noun supply"













